export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const SET_EXPENSES = 'SET_EXPENSES';
export const FETCH_EXPENSES_FAILED = 'FETCH_EXPENSES_FAILED';

export const SET_CATEGORY = 'SET_CATEGORY';
export const FETCH_CATEGORY_FAILED = 'FETCH_CATEGORY_FAILED';

export const SET_BUDGET = 'SET_BUDGET';
export const FETCH_BUDGET_FAILED = 'FETCH_BUDGET_FAILED';